version: '3.8'

services:
  app:
    build: .
    container_name: split_fare_api
    image: split_fare_backend
    ports:
      - "8000:80"
    depends_on:
      - mongo
    environment:
      - ENVIRONMENT=DEV

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
